import Image from "next/image";
import { getBase64 } from "@/lib/image";
import { cn } from "@/lib/utils";

type PostThumbnailProps = {
  title?: string;
  author?: string;
  fromUrl?: string;
  src: string;
  hasInfo?: boolean;
  size?: "sm" | "md" | "lg";
  rounded?: boolean;
};

const PostThumbnail = async ({
  title,
  src,
  hasInfo = true,
  size = "md",
  rounded = false,
}: PostThumbnailProps) => {
  const { url, width, height } = await getBase64(src);
  const h = size === "md" ? 500 : size === "sm" ? 200 : height;
  const w = size === "md" ? 375 : size === "sm" ? 300 : width;

  return (
    <div>
      <Image
        blurDataURL={url}
        quality={100}
        src={src}
        placeholder="blur"
        className={cn(
          "aspect-[4/3] w-full object-cover shadow-md",
          rounded && "rounded",
        )}
        width={w}
        height={h}
        alt={`${title}-image`}
        priority
        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 60vw"
      />
      {hasInfo && (
        <div className="mt-2 text-center text-xs text-gray-400 dark:text-gray-500 lg:mt-4 lg:text-sm">
          Image generated by Midjourney
        </div>
      )}
    </div>
  );
};

export default PostThumbnail;
