import "@/styles/globals.css";

import type { Metadata } from "next";
import { Fira_Code, Space_Mono, DM_Serif_Display } from "next/font/google";

import Header from "@/components/nav/header";
import ThemeProvider from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer";

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-code",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
  weight: ["400", "700"],
});

const dmSerifDisplay = DM_Serif_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          firaCode.variable,
          dmSerifDisplay.variable,
          spaceMono.variable,
          "relative min-h-full max-w-[100vw]",
        )}
      >
        <ThemeProvider>
          <main className="flex min-h-screen flex-col">
            <Header />
            <div className="mx-6 mb-12 mt-8 grow md:mx-12 lg:mx-0 lg:mt-32">
              {props.children}
            </div>
            <Footer hasMarginBottom={false} />
          </main>

          <Toaster />
          {props.modal}
        </ThemeProvider>
      </body>
    </html>
  );
}
